### ISSUE TITLE
Add interface parameterization to deploy.sh

### ISSUE THREAD

**Issue by trozet** [trozet/bgs_vagrant#11]
Currently networks are defined dynamically and in order for the first 3-4 jumphost NICs that are UP with an ip address.  The assumed order is Admin (PXE), Private (+Storage if only 3 networks), Public, Storage (optional).

deploy.sh should be more flexible so that a user can define which NIC of the jumphost should be which opnfv network.  Proposal:
./deploy.sh -admin_nic eth0 -private_nic eth1 -public_nic eth2

If no "-storage_nic" is defined, storage will be consolidated over the private network.  deploy.sh should also take care of ensuring those nic's provided as script arguments are real NICs on that jumphost, and are UP with an ip address.

**Comment by trozet** [comment]
I think this actually fairly easy to do by just changing the bridging of the VM to the specified baremetal NIC.  That way the Vagrant VM keeps the same interface order, but is mapped to a different order on baremetal.  This might create complications somewhere down the road after deploy.sh so going to open this as a feature branch until fully tested.

**Comment by ibravo** [comment]
One option is to list the order of the interfaces as is read from the code, so that the user knows what interface is expected to be considered the Admin NIC, rather than just getting a failure message.

Print the output of:
output=`ifconfig | grep -E "^[a-zA-Z0-9]+:"| grep -Ev "lo|tun|virbr|vboxnet" | awk '{print $1}' | sed 's/://'`

**Comment by trozet** [comment]
project has been deprecated in favor of OPNFV Genesis
